# lychee.toml

max_retries = 3             
retry_wait_time = 10

# Remap absolute paths to add it to mdx
remap = [ "^(file:///.*valkey-glide-docs/src/content/docs/.*)$ $1.mdx" ]

# Exclude specific files from being scanned
exclude_path = [
    # Excluding languages folder until removal
    "languages/"
]

# Exclude specific URLs/links (RegEx)
exclude = [
    # API Documentation exclusions
    '.*/languages/java/api',
    '.*/languages/nodejs/api',
    '.*/languages/python/api',

    # Localhost URLs
    'http://localhost.*'
]
