site_name: GLIDE for Valkey - API Documentation
site_url: https://glide.valkey.io/languages/python/api
repo_url: https://github.com/valkey-io/valkey-glide
repo_name: GitHub
docs_dir: mkdocs
nav:
  - Overview: /languages/python/api/

theme:
  name: material
  palette:
    scheme: valkey-glide
  favicon: valkey-favicon.svg
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - navigation.path
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
  highlightjs: true
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            [
              "valkey-glide/python/glide-shared",
              "valkey-glide/python/glide-async/python",
              "valkey-glide/python/glide-sync/",
            ]
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            docstring_style: google
            members_order: source
            filters:
              - "!^_"
  - api-autonav:
      nav_item_prefix: ""
      modules:
        - valkey-glide/python/glide-async/python/glide
        - valkey-glide/python/glide-sync/glide_sync
        - valkey-glide/python/glide-shared/glide_shared
      # Exclude internal modules and files that are not relevant to users
      exclude:
        - "re:.*\\.protobuf.*"
        - "re:.*\\.protobuf_codec$"
        - "re:.*\\.utils$"
      exclude_private: true
extra:
  generator: false
extra_css:
  - style.css
