name: Check Code Examples

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  csharp:
    uses: ./.github/workflows/check-csharp-examples.yml
  node:
    uses: ./.github/workflows/check-node-examples.yml
